import { test, expect } from '@playwright/test';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { expectFontsLoaded } from './font-readiness.js';

async function saved(page, room = 'ALLOCATION-RC') { return page.evaluate(key => JSON.parse(localStorage.getItem(`sanpo-react:v1:${key}:room`)), room); }
test('register, fill seats, independent team, roles, fixed participants, menus and reload', async ({ page }, testInfo) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?room=ALLOCATION-RC');
  await page.getByRole('button', { name: '参加者を追加', exact: true }).click();
  await page.getByRole('button', { name: '追加', exact: true }).click();
  const registration = page.getByRole('dialog', { name: '参加者登録' });
  await expect(registration).toBeVisible();
  await registration.getByRole('textbox', { name: '参加者（改行区切り）', exact: true }).fill('仮参加者A\n仮参加者B\n仮参加者C\n仮参加者D');
  await registration.getByRole('textbox', { name: '車出し可能な参加者', exact: true }).fill('仮参加者A');
  await registration.getByRole('textbox', { name: '1年生', exact: true }).fill('仮参加者B');
  await registration.getByRole('button', { name: '登録', exact: true }).click();
  await expect(registration).toHaveCount(0);
  await page.getByRole('tab', { name: '車割', exact: true }).click();
  await expect(page.getByRole('region', { name: '仮参加者A車', exact: true })).toBeVisible();
  const car = page.getByRole('region', { name: '仮参加者A車', exact: true });
  await expect(car.getByRole('button', { name: '削除', exact: true })).toHaveClass(/cds--btn--danger-ghost/);
  await expect(page.getByRole('button', { name: 'ランダム割り当て', exact: true })).toHaveClass(/cds--btn--tertiary/);
  await car.getByRole('button', { name: /空席 3/ }).click();
  await car.getByRole('button', { name: '仮参加者Bを仮参加者A車に追加', exact: true }).click();
  await car.getByRole('button', { name: '仮参加者Cを仮参加者A車に追加', exact: true }).click();
  await car.getByRole('button', { name: '仮参加者Dを仮参加者A車に追加', exact: true }).click();
  await expect(car.getByRole('button', { name: /空席/ })).toHaveCount(0);
  await car.getByRole('button', { name: '仮参加者Bの固定', exact: true }).click();
  await car.getByRole('button', { name: '仮参加者Bの操作', exact: true }).click();
  await page.getByRole('menuitem', { name: '運転手にする', exact: true }).click();
  let room = await saved(page);
  const a = Object.values(room.participants).find(person => person.name === '仮参加者A');
  const b = Object.values(room.participants).find(person => person.name === '仮参加者B');
  const carGroupId = room.allocations.car.placements[a.id].groupId;
  expect(room.allocations.car.groups[carGroupId].ownerId).toBe(a.id);
  expect(room.allocations.car.placements[a.id].driver).toBe(true);
  expect(room.allocations.car.placements[b.id].driver).toBe(true);
  expect(Object.values(room.allocations.car.placements).filter(placement => placement.driver).length).toBeGreaterThanOrEqual(2);
  expect(room.participants[b.id].locked).toBe(true);
  expect(Object.values(room.allocations.team.placements).every(p => p.kind === 'waiting')).toBe(true);
  await page.getByRole('button', { name: 'ランダム割り当て', exact: true }).click();
  await page.getByRole('dialog', { name: 'ランダム割り当て' }).getByRole('button', { name: '実行', exact: true }).click();
  room = await saved(page);
  expect(room.allocations.car.placements[b.id].groupId).toBe(carGroupId);
  expect(room.allocations.car.placements[b.id].driver).toBe(true);
  await page.getByRole('tab', { name: '班割', exact: true }).click();
  await page.getByRole('button', { name: '班を追加', exact: true }).click();
  const groupDialog = page.getByRole('dialog', { name: '班を追加' });
  await groupDialog.getByRole('combobox', { name: '班長', exact: true }).selectOption(b.id);
  await groupDialog.getByRole('button', { name: '追加', exact: true }).click();
  await expect(page.getByRole('region', { name: '仮参加者B班', exact: true })).toBeVisible();
  room = await saved(page);
  expect(room.allocations.car.placements[b.id].driver).toBe(true);
  expect(room.allocations.team.placements[b.id].driver).toBe(true);
  expect(room.allocations.car.placements[b.id].groupId).not.toBe(room.allocations.team.placements[b.id].groupId);
  await page.getByRole('tab', { name: '車割', exact: true }).click();
  await car.getByRole('button', { name: '仮参加者Aの操作', exact: true }).click();
  await page.getByRole('menuitem', { name: '運転手を外す', exact: true }).click();
  room = await saved(page);
  expect(room.allocations.car.groups[carGroupId].ownerId).toBe(a.id);
  expect(room.allocations.car.placements[a.id].driver).toBe(false);
  expect(room.allocations.car.placements[b.id].driver).toBe(true);
  await car.getByRole('button', { name: '仮参加者A車の定員を変更', exact: true }).click();
  const capacityDialog = page.getByRole('dialog', { name: '定員を変更' });
  await capacityDialog.getByRole('spinbutton', { name: '定員', exact: true }).fill('2');
  await capacityDialog.getByRole('button', { name: '保存', exact: true }).click();
  room = await saved(page);
  expect(room.allocations.car.groups[carGroupId].capacity).toBe(2);
  expect(Object.entries(room.allocations.car.placements).filter(([id, placement]) => id !== a.id && placement.groupId === carGroupId)).toHaveLength(2);
  expect(room.allocations.team.placements[b.id].groupId).not.toBe(room.allocations.car.placements[b.id].groupId);
  await car.getByRole('button', { name: '仮参加者Bの操作', exact: true }).click();
  await page.keyboard.press('Escape');
  await expect(car.getByRole('button', { name: '仮参加者Bの操作', exact: true })).toBeFocused();
  await car.getByRole('button', { name: '仮参加者Bの操作', exact: true }).click();
  await page.getByRole('menuitem', { name: 'メモ', exact: true }).click();
  const editor = page.getByRole('dialog', { name: '参加者を編集' });
  await editor.getByRole('textbox', { name: 'メモ', exact: true }).fill('日本語のメモ');
  await editor.getByRole('button', { name: '保存', exact: true }).click();
  await expect(editor).toHaveCount(0);
  await expect(car).toContainText('日本語のメモ');
  for (const theme of ['g10', 'g100']) {
    if (theme === 'g100') { await page.getByRole('button', { name: 'ユーティリティメニュー' }).click(); await page.getByRole('menuitem', { name: 'ダークモードに切り替え' }).click(); }
    await expect(page.getByRole('textbox', { name: '企画名' })).toHaveCSS('background-color', theme === 'g100' ? 'rgb(38, 38, 38)' : 'rgb(255, 255, 255)');
    const geometry = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth, overflow: [...document.querySelectorAll('body *')].map(node => ({ tag: node.tagName, className: String(node.className), text: node.textContent?.slice(0, 60), x: node.getBoundingClientRect().x, right: node.getBoundingClientRect().right, width: node.getBoundingClientRect().width, position: getComputedStyle(node).position })).filter(node => node.width > 0 && node.right > innerWidth + 1).slice(0, 30) }));
    await testInfo.attach(`geometry-${theme}`, { body: JSON.stringify(geometry, null, 2), contentType: 'application/json' });
    expect(geometry.scrollWidth, JSON.stringify(geometry)).toBeLessThanOrEqual(geometry.width);
    await expectFontsLoaded(page);
    await page.screenshot({ path: join(tmpdir(), 'circle-react-migration-evidence', `allocation-${testInfo.project.name}-${theme}.png`), fullPage: true });
  }
  await page.reload();
  await expect(page.getByRole('region', { name: '仮参加者A車', exact: true })).toContainText('日本語のメモ');
  expect(errors).toEqual([]);
});
