import {test,expect} from '@playwright/test';
import {seedVehicleCostRoom} from './vehicle-cost-fixture.js';
async function open(page,info,task=''){const id=`H-HISTORY-${info.project.name}-${info.testId}-${info.retry}`;await seedVehicleCostRoom(page,{roomId:id});await page.goto(`/?room=${id}&section=history-settings${task?`&task=${task}`:''}`);return id;}
const readRoom=(page,id)=>page.evaluate(id=>JSON.parse(localStorage.getItem(`sanpo-react:v1:${id}:room`)),id);
test('history is a local page and manual snapshot visibly updates without shared write',async({page},info)=>{const id=await open(page,info),before=await readRoom(page,id);await expect(page.getByRole('heading',{level:1,name:'履歴',exact:true})).toBeVisible();await expect(page.getByRole('main')).toContainText('この端末');await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'現在の状態を保存',exact:true}).click();await expect(page.getByRole('main')).toContainText('現在の状態と一致');expect(await readRoom(page,id)).toEqual(before);await page.reload();await expect(page.getByRole('main')).toContainText('現在の状態と一致');await expect(page.getByRole('dialog')).toHaveCount(0);});
test('corrupt history is explained without silently replacing stored data',async({page},info)=>{const id=await open(page,info);await page.evaluate(id=>localStorage.setItem(`syawari_history_${id}`,'{broken'),id);await page.reload();await expect(page.getByRole('alert')).toContainText('読み込めません');expect(await page.evaluate(id=>localStorage.getItem(`syawari_history_${id}`),id)).toBe('{broken');await expect(page.getByRole('button',{name:'現在の状態を保存',exact:true})).toBeDisabled();});
test('malformed history labels stay visible unavailable and byte-preserved',async({page},info)=>{
  const id=await open(page,info),before=await readRoom(page,id),errors=[];page.on('pageerror',error=>errors.push(error.message));
  const raw=JSON.stringify([{time:1,data:{roomName:{bad:true},participants:{}}},{time:2,data:before}]);
  await page.evaluate(({id,raw})=>localStorage.setItem(`syawari_history_${id}`,raw),{id,raw});await page.reload();
  await expect(page.getByRole('heading',{level:1,name:'履歴',exact:true})).toBeVisible();
  const rows=page.getByRole('list',{name:'この端末の保存済み履歴'}).getByRole('listitem');await expect(rows).toHaveCount(2);
  await expect(rows.first()).toContainText('復元できません');await expect(rows.first().getByRole('button',{name:'この状態を復元',exact:true})).toBeDisabled();
  await expect(rows.last().getByRole('button',{name:'この状態を復元',exact:true})).toBeEnabled();
  expect(await page.evaluate(id=>localStorage.getItem(`syawari_history_${id}`),id)).toBe(raw);expect(await readRoom(page,id)).toEqual(before);expect(errors).toEqual([]);
});
test('restore cancel returns focus without writing',async({page},info)=>{const id=await open(page,info);await page.getByRole('button',{name:'現在の状態を保存',exact:true}).click();const before=await readRoom(page,id);const trigger=page.getByRole('button',{name:'この状態を復元',exact:true});await trigger.click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('実際の集金や支払いは取り消されません');await expect(dialog.getByRole('button',{name:'この状態を復元',exact:true})).toBeDisabled();await dialog.press('Escape');await expect(trigger).toBeFocused();expect(await readRoom(page,id)).toEqual(before);});
test('restore is explicit and undo is only available in the same unchanged session',async({page},info)=>{const id=await open(page,info);await page.getByRole('button',{name:'現在の状態を保存',exact:true}).click();const original=await readRoom(page,id);await page.evaluate(id=>{const key=`sanpo-react:v1:${id}:room`,room=JSON.parse(localStorage.getItem(key));room.roomName='復元前の変更';localStorage.setItem(key,JSON.stringify(room));},id);await page.reload();await page.getByRole('button',{name:'この状態を復元',exact:true}).click();const dialog=page.getByRole('dialog'),checkbox=dialog.getByRole('checkbox');await checkbox.focus();await checkbox.press('Space');await dialog.getByRole('button',{name:'この状態を復元',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'復元を取り消す',exact:true})).toBeVisible();expect((await readRoom(page,id)).roomName).toBe(original.roomName);await page.reload();await expect(page.getByRole('button',{name:'復元を取り消す',exact:true})).toHaveCount(0);expect((await readRoom(page,id)).participants).toBeTruthy();});
test('sample selection and confirmation cancel preserve the project',async({page},info)=>{const id=await open(page,info);await page.getByRole('link',{name:'サンプルデータ',exact:true}).click();await expect(page.getByRole('heading',{level:1,name:'サンプルデータ',exact:true})).toBeFocused();const before=await readRoom(page,id);await page.getByRole('radio',{name:'フォーム連携サンプル',exact:true}).focus();await page.getByRole('radio',{name:'フォーム連携サンプル',exact:true}).press('Space');await page.getByRole('button',{name:'置換内容を確認',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'サンプルで置き換える',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'キャンセル',exact:true}).click();await expect(page.getByRole('heading',{level:1,name:'サンプルデータ',exact:true})).toBeVisible();expect(await readRoom(page,id)).toEqual(before);await expect(page.getByRole('radio',{name:'フォーム連携サンプル',exact:true})).toBeChecked();await expect(page.getByRole('button',{name:'置換内容を確認',exact:true})).toBeFocused();});
test('sample is separate from routine utilities and explicit replacement retains form capability',async({page},info)=>{const id=await open(page,info,'sample');await page.getByRole('button',{name:'ユーティリティメニュー',exact:true}).click();await expect(page.getByRole('menuitem',{name:'サンプルデータ',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await page.getByRole('radio',{name:'フォーム連携サンプル',exact:true}).focus();await page.getByRole('radio',{name:'フォーム連携サンプル',exact:true}).press('Space');await page.getByRole('button',{name:'置換内容を確認',exact:true}).click();const dialog=page.getByRole('dialog'),checkbox=dialog.getByRole('checkbox');await checkbox.focus();await checkbox.press('Space');await dialog.getByRole('button',{name:'サンプルで置き換える',exact:true}).click();await expect(dialog).toHaveCount(0);expect((await readRoom(page,id)).meta.applicationSync).toBeTruthy();await expect(page.getByRole('main')).toContainText('記録が更新されています');await expect(page.getByRole('button',{name:'現在の内容を確認',exact:true})).toBeVisible();await expect(page.getByRole('main')).not.toContainText('変更範囲を確認できません');});
