import { test, expect } from '@playwright/test';
test('five-screen Carbon consistency at mobile width', async ({ page }) => {
  const roomId = 'VISUAL-CONSISTENCY-RC';
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/?room=${roomId}&view=participants`);
  await page.getByRole('button', { name: 'ユーティリティメニュー' }).click();
  await page.getByRole('menuitem', { name: 'サンプルデータ', exact: true }).click();
  const sample = page.getByRole('dialog', { name: 'サンプルデータ' });
  await sample.getByRole('radio', { name: '通常サンプル', exact: true }).check({ force: true });
  await sample.getByRole('button', { name: 'サンプルを入れる', exact: true }).click();

  const tabs = page.getByRole('tablist', { name: '画面切り替え' });
  await expect(tabs.getByRole('tab')).toHaveCount(4);
  await expect(page.getByRole('heading', { name: '参加者', exact: true })).toHaveCount(0);
  const participantSummary = page.locator('.participants-page > .section-heading p');
  await expect(participantSummary).toContainText(/参加者\s*\d+人/);
  expect(await participantSummary.evaluate(element => getComputedStyle(element).marginBlockStart)).toBe('0px');
  const participantInset = (await participantSummary.boundingBox()).x;
  await expect(page.getByText('参加者を追加してください。', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '追加', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '追加', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '参加者登録' })).toBeVisible();
  await page.getByRole('dialog', { name: '参加者登録' }).getByRole('button', { name: 'キャンセル' }).click();

  await page.getByRole('tab', { name: '班割', exact: true }).click();
  await expect(page.getByRole('heading', { name: '班割', exact: true })).toHaveCount(0);
  await expect(page.locator('.allocation-page[aria-label="班割"] .allocation-toolbar-summary')).toContainText(/\d+人・\d+班/);
  const randomize = page.getByRole('button', { name: 'ランダム割り当て', exact: true });
  await expect(randomize).toHaveClass(/cds--btn--ghost/);
  await randomize.hover();
  expect(await randomize.evaluate(element => getComputedStyle(element).cursor)).toBe('pointer');
  await randomize.focus();
  await expect(randomize).toBeFocused();
  await page.getByRole('button', { name: /班の操作$/ }).first().click();
  const removeGroup = page.getByRole('menuitem', { name: '削除', exact: true }).first();
  await expect(removeGroup).toBeVisible();
  await expect(removeGroup.locator('xpath=ancestor::li[1]')).toHaveClass(/--danger/);
  const seatToggle = page.locator('.empty-seats-action').first();
  await seatToggle.click();
  await expect(seatToggle).toHaveAttribute('aria-expanded', 'true');

  await page.getByRole('tab', { name: '精算', exact: true }).click();
  await expect(page.getByRole('heading', { name: '各車への支払い', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '集金チェック', exact: true })).toBeVisible();
  const settlementInset = (await page.getByRole('heading', { name: '各車への支払い', exact: true }).boundingBox()).x;
  expect(Math.abs(settlementInset - participantInset)).toBeLessThanOrEqual(1);
  const settingsButton = page.getByRole('button', { name: '精算設定を編集', exact: true });
  await expect(settingsButton).toHaveClass(/cds--btn--ghost/);
  expect((await settingsButton.boundingBox()).width).toBeLessThan((await page.locator('.settlement-card').nth(1).boundingBox()).width * 0.6);
  await expect(page.locator('.settlement-collection-summary')).toContainText(/\d+\/\d+人/);
  const collectionTrigger = page.getByRole('button', { name: '集金を確認', exact: true });
  await collectionTrigger.click();
  const collectionDialog = page.getByRole('dialog', { name: '集金を確認' });
  await expect(collectionDialog).toBeVisible();
  const switcher = collectionDialog.getByRole('tablist', { name: '集金対象者の表示' });
  await expect(switcher.getByRole('tab', { name: 'すべて' })).toBeVisible();
  await expect(switcher.getByRole('tab', { name: '未回収' })).toBeVisible();
  await switcher.getByRole('tab', { name: '未回収' }).click();
  await expect(switcher.getByRole('tab', { name: '未回収' })).toHaveAttribute('aria-selected', 'true');
  await switcher.getByRole('tab', { name: 'すべて' }).click();
  await expect(collectionDialog.locator('.settlement-collection-row.excluded .cds--tag').first()).toBeVisible();
  await collectionDialog.getByRole('button', { name: '閉じる', exact: true }).last().click();
  const paymentCard = page.locator('.settlement-car').first();
  await expect(paymentCard.getByRole('button', { name: '費用を入力', exact: true })).toHaveClass(/cds--btn--ghost/);
  await paymentCard.getByRole('button', { name: '費用を入力', exact: true }).click();
  const editCost = page.getByRole('dialog', { name: /藤原 拓海車/ });
  await expect(editCost).toBeVisible();
  await editCost.getByRole('button', { name: 'キャンセル', exact: true }).click();
  const expand = paymentCard.getByRole('button', { name: /割勘.*部費/ });
  await expand.click();
  await expect(expand).toHaveAttribute('aria-expanded', 'true');
  await expect(paymentCard.getByRole('heading', { name: '割勘', exact: true })).toBeVisible();
  await expect(paymentCard.getByRole('heading', { name: '部費', exact: true })).toBeVisible();
  await expect(paymentCard.getByText('費用小計', { exact: true })).toHaveCount(0);
  await expect(paymentCard.getByText('支払総額', { exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
