import { test, expect } from '@playwright/test';
import { navigateToProjectSection } from './project-navigation.js';
import { editFee } from './vehicle-cost-fixture.js';
test('five-screen Carbon consistency at mobile width', async ({ page }) => {
  const roomId = 'VISUAL-CONSISTENCY-RC';
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/?room=${roomId}&view=participants`);
  await page.getByRole('button', { name: 'ユーティリティメニュー' }).click();
  await page.getByRole('menuitem', { name: 'サンプルデータ', exact: true }).click();
  const sample = page.getByRole('dialog', { name: 'サンプルデータ' });
  await sample.getByRole('radio', { name: '通常サンプル', exact: true }).check({ force: true });
  await sample.getByRole('button', { name: 'サンプルを入れる', exact: true }).click();

  await expect(page.getByRole('navigation', { name: '企画内ナビゲーション' }).getByRole('link')).toHaveText(['参加者','車割','班割','車両費用','精算','概要','履歴']);
  const participantHeading = page.getByRole('heading', { name: '参加者', exact: true });
  await expect(participantHeading).toBeVisible();
  const participantInset = (await participantHeading.boundingBox()).x;
  await expect(page.getByText('参加者を追加してください。', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '参加者を追加', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '参加者を追加', exact: true }).click();
  await expect(page.getByRole('form', { name: '参加者を登録' })).toBeVisible();
  await page.getByRole('form', { name: '参加者を登録' }).getByRole('button', { name: 'キャンセル' }).click();

  await navigateToProjectSection(page, '班割');
  const teamHeading = page.getByRole('heading', { name: '班割', exact: true });
  await expect(teamHeading).toBeVisible();
  expect(Math.abs((await teamHeading.boundingBox()).x - participantInset)).toBeLessThanOrEqual(1);
  const randomize = page.getByRole('button', { name: 'ランダム割り当て', exact: true });
  await randomize.hover();
  expect(await randomize.evaluate(element => getComputedStyle(element).cursor)).toBe('pointer');
  await randomize.focus();
  await expect(randomize).toBeFocused();
  await page.getByRole('button', { name: /班の操作$/ }).first().click();
  const removeGroup = page.getByRole('menuitem', { name: '削除', exact: true }).first();
  await expect(removeGroup).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: /班の詳細$/ }).first().click();
  const assignment = page.getByRole('link', { name: '参加者を割り当て', exact: true });
  if (await assignment.count()) {
    await assignment.click();
    await expect(page.getByRole('list', { name: /^未割り当て/ })).toBeVisible();
    await expect(page).toHaveURL(/task=assign/);
  } else {
    await expect(page.getByRole('main')).toContainText('空き0人');
  }

  await navigateToProjectSection(page, '精算');
  await expect(page.getByRole('heading', { level: 1, name: '精算', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '各車への支払い', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '集金チェック', exact: true })).toBeVisible();
  const settlementInset = (await page.getByRole('heading', { level: 1, name: '精算', exact: true }).boundingBox()).x;
  expect(Math.abs(settlementInset - participantInset)).toBeLessThanOrEqual(1);
  const settingsButton = page.getByRole('link', { name: '精算ルール', exact: true });
  await expect(settingsButton).toHaveAttribute('href', /section=settlement.*task=rules/);
  expect((await settingsButton.boundingBox()).height).toBeGreaterThanOrEqual(44);
  expect((await settingsButton.boundingBox()).y).toBeLessThan((await page.getByRole('heading', { name: '各車への支払い', exact: true }).boundingBox()).y);
  await expect(page.locator('.settlement-collection-summary')).toContainText(/\d+\/\d+人/);
  const collectionTrigger = page.getByRole('button', { name: '集金を確認', exact: true });
  await collectionTrigger.click();
  const collectionDialog = page.getByRole('dialog', { name: '集金を確認' });
  await expect(collectionDialog).toBeVisible();
  const switcher = collectionDialog.getByRole('tablist', { name: '集金対象者の表示' });
  await expect(switcher.getByRole('tab', { name: 'すべて' })).toBeVisible();
  await expect(switcher.getByRole('tab', { name: '未回収' })).toBeVisible();
  await switcher.getByRole('tab', { name: '未回収' }).click();
  await expect(switcher.getByRole('tab', { name: '未回収' })).toHaveAttribute('aria-selected', 'true');
  await switcher.getByRole('tab', { name: 'すべて' }).click();
  await expect(collectionDialog.locator('.settlement-collection-row.excluded .cds--tag').first()).toBeVisible();
  await collectionDialog.getByRole('button', { name: '閉じる', exact: true }).last().click();
  const paymentCard = page.locator('.settlement-car').first();
  await expect(paymentCard.getByRole('button', { name: /費用を入力$/ })).toHaveClass(/cds--btn--ghost/);
  await paymentCard.getByRole('button', { name: /費用を入力$/ }).click();
  const editCost = page.getByRole('heading', {level:1,name:/藤原 拓海車の費用/});
  await expect(editCost).toBeVisible();
  await editFee(page,'移動条件');
  await page.getByRole('button', { name: 'キャンセル', exact: true }).click();
  const expand = paymentCard.getByRole('button', { name: /割勘.*部費/ });
  await expand.click();
  await expect(expand).toHaveAttribute('aria-expanded', 'true');
  await expect(paymentCard.getByRole('heading', { name: '割勘', exact: true })).toBeVisible();
  await expect(paymentCard.getByRole('heading', { name: '部費', exact: true })).toBeVisible();
  await expect(paymentCard.getByText('費用小計', { exact: true })).toHaveCount(0);
  await expect(paymentCard.getByText('支払総額', { exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
