import { test, expect } from '@playwright/test';
test('five-screen Carbon consistency at mobile width', async ({ page }) => {
  const roomId = 'VISUAL-CONSISTENCY-RC';
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/?room=${roomId}&view=participants`);
  await page.getByRole('button', { name: 'ユーティリティメニュー' }).click();
  await page.getByRole('menuitem', { name: 'サンプルデータ', exact: true }).click();
  const sample = page.getByRole('dialog', { name: 'サンプルデータ' });
  await sample.getByRole('radio', { name: '通常サンプル', exact: true }).check({ force: true });
  await sample.getByRole('button', { name: 'サンプルを入れる', exact: true }).click();

  const tabs = page.getByRole('tablist', { name: '画面切り替え' });
  await expect(tabs.getByRole('tab')).toHaveCount(4);
  const participantHeading = page.getByRole('heading', { name: '参加者', exact: true });
  await expect(participantHeading).toBeVisible();
  const participantInset = (await participantHeading.boundingBox()).x;
  await expect(page.getByText('参加者を追加してください。', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '追加', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '追加', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '参加者登録' })).toBeVisible();
  await page.getByRole('dialog', { name: '参加者登録' }).getByRole('button', { name: 'キャンセル' }).click();

  await page.getByRole('tab', { name: '班割', exact: true }).click();
  const teamHeading = page.getByRole('heading', { name: '班割', exact: true });
  await expect(teamHeading).toBeVisible();
  expect(Math.abs((await teamHeading.boundingBox()).x - participantInset)).toBeLessThanOrEqual(1);
  const randomize = page.getByRole('button', { name: 'ランダム割り当て', exact: true });
  await expect(randomize).toHaveClass(/cds--btn--tertiary/);
  await randomize.hover();
  expect(await randomize.evaluate(element => getComputedStyle(element).cursor)).toBe('pointer');
  await randomize.focus();
  await expect(randomize).toBeFocused();
  await page.getByRole('button', { name: /班の操作$/ }).first().click();
  const removeGroup = page.getByRole('menuitem', { name: '削除', exact: true }).first();
  await expect(removeGroup).toBeVisible();
  await expect(removeGroup.locator('xpath=ancestor::li[1]')).toHaveClass(/--danger/);
  const seatToggle = page.locator('.empty-seats-action').first();
  await seatToggle.click();
  await expect(seatToggle).toHaveAttribute('aria-expanded', 'true');

  await page.getByRole('tab', { name: '精算', exact: true }).click();
  await expect(page.getByRole('heading', { name: '精算状況', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '精算設定', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '集金チェック', exact: true })).toBeVisible();
  const settlementInset = (await page.getByRole('heading', { name: '精算状況', exact: true }).boundingBox()).x;
  expect(Math.abs(settlementInset - participantInset)).toBeLessThanOrEqual(1);
  await expect(page.getByRole('button', { name: '精算設定を編集', exact: true })).toHaveClass(/cds--btn--tertiary/);
  const settingsButton = page.getByRole('button', { name: '精算設定を編集', exact: true });
  expect((await settingsButton.boundingBox()).width).toBeLessThan((await page.locator('.settlement-card').nth(1).boundingBox()).width * 0.6);
  const switcher = page.getByRole('tablist', { name: '集金チェックの表示' });
  await expect(switcher.getByRole('tab', { name: 'すべて' })).toBeVisible();
  await expect(switcher.getByRole('tab', { name: '未回収のみ' })).toBeVisible();
  await switcher.getByRole('tab', { name: '未回収のみ' }).click();
  await expect(switcher.getByRole('tab', { name: '未回収のみ' })).toHaveAttribute('aria-selected', 'true');
  await switcher.getByRole('tab', { name: 'すべて' }).click();
  await expect(page.locator('.settlement-check-row.excluded .cds--tag').first()).toBeVisible();
  const paymentCard = page.locator('.settlement-car').first();
  const paidButton = paymentCard.getByRole('button', { name: '支払い済みにする', exact: true });
  await paidButton.click();
  await expect(paymentCard.getByText('支払い済み', { exact: true })).toBeVisible();
  await paymentCard.getByRole('button', { name: '未払いに戻す', exact: true }).click();
  await expect(paymentCard.getByText('未払い', { exact: true })).toBeVisible();
  await expect(paymentCard.getByRole('button', { name: '費用を編集', exact: true })).toHaveClass(/cds--btn--ghost/);
  await paymentCard.getByRole('button', { name: '費用を編集', exact: true }).click();
  const editCost = page.getByRole('dialog', { name: /藤原 拓海車/ });
  await expect(editCost).toBeVisible();
  await editCost.getByRole('button', { name: 'キャンセル', exact: true }).click();
  const expand = paymentCard.getByRole('button', { name: /内訳/ });
  await expand.click();
  await expect(expand).toHaveAttribute('aria-expanded', 'true');
  await expect(paymentCard.getByText('合計', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
