import test from 'node:test';
import assert from 'node:assert/strict';
import {createOperationsFixture} from './helpers/settlement-operations-fixture.mjs';
import {createOperationsCache} from '../src/ui/settlement-operations-draft.js';
import {createSettlementOperationController} from '../src/ui/settlement-operation-controller.js';
import {createProjectHistoryController} from '../src/ui/project-history-controller.js';
async function setup(t,options){const r=await createOperationsFixture(options);t.after(r.dispose);const cache=createOperationsCache({roomId:r.runtime.roomId,storage:()=>r.rawStorage}),operations=createSettlementOperationController({runtime:r.runtime,cache});t.after(operations.dispose);const history=createProjectHistoryController({runtime:r.runtime,operations,rawStorage:()=>r.rawStorage});t.after(history.dispose);return {...r,cache,operations,history};}
test('history entry has no writes and manual save deduplicates with current business marker',async t=>{const r=await setup(t);let writes=0;r.runtime.store.subscribeIntents(()=>writes++);assert.equal(r.history.getSnapshot().items.length,0);assert.equal(r.history.saveSnapshot(),true);assert.equal(writes,0);assert.equal(r.history.getSnapshot().items[0].current,true);assert.equal(r.history.saveSnapshot(),true);assert.equal(r.history.getSnapshot().items.length,1);r.runtime.store.command('rename',{name:'新企画'});assert.equal(r.history.getSnapshot().items[0].current,false);});
test('history save requires readback',async t=>{const r=await setup(t);const native=r.rawStorage.setItem;r.rawStorage.setItem=(key,value)=>{if(key===r.runtime.history.key)throw Error('quota');return native(key,value);};assert.equal(r.history.saveSnapshot(),false);assert.ok(r.history.getSnapshot().loadIssue);assert.equal(r.history.getSnapshot().items.length,0);});
test('corrupt history is not repaired and foreign pending write blocks snapshot',async t=>{const r=await setup(t);r.rawStorage.setItem(r.runtime.history.key,'corrupt');assert.equal(r.history.saveSnapshot(),false);assert.equal(r.rawStorage.getItem(r.runtime.history.key),'corrupt');r.rawStorage.removeItem(r.runtime.history.key);r.runtime.storage.write('outbox',{id:'foreign'});assert.equal(r.history.saveSnapshot(),false);assert.equal(r.runtime.history.read().length,0);});
test('history uses existing twenty-item limit',async t=>{const r=await setup(t);for(let index=0;index<23;index++){r.runtime.store.command('rename',{name:`企画${index}`});assert.equal(r.history.saveSnapshot(),true);}assert.equal(r.history.getSnapshot().items.length,20);});
