import test from 'node:test';
import assert from 'node:assert/strict';
import {createOperationsFixture} from './helpers/settlement-operations-fixture.mjs';
import {createOperationsCache} from '../src/ui/settlement-operations-draft.js';
import {createSettlementOperationController} from '../src/ui/settlement-operation-controller.js';
import {createProjectHistoryController} from '../src/ui/project-history-controller.js';
async function setup(t,options){const r=await createOperationsFixture(options);t.after(r.dispose);const cache=createOperationsCache({roomId:r.runtime.roomId,storage:()=>r.rawStorage}),operations=createSettlementOperationController({runtime:r.runtime,cache});t.after(operations.dispose);const history=createProjectHistoryController({runtime:r.runtime,operations,rawStorage:()=>r.rawStorage});t.after(history.dispose);return {...r,cache,operations,history};}
test('history entry has no writes and manual save deduplicates with current business marker',async t=>{const r=await setup(t);let writes=0;r.runtime.store.subscribeIntents(()=>writes++);assert.equal(r.history.getSnapshot().items.length,0);assert.equal(r.history.saveSnapshot(),true);assert.equal(writes,0);assert.equal(r.history.getSnapshot().items[0].current,true);assert.equal(r.history.saveSnapshot(),true);assert.equal(r.history.getSnapshot().items.length,1);r.runtime.store.command('rename',{name:'新企画'});assert.equal(r.history.getSnapshot().items[0].current,false);});
test('history save requires readback',async t=>{const r=await setup(t);const native=r.rawStorage.setItem;r.rawStorage.setItem=(key,value)=>{if(key===r.runtime.history.key)throw Error('quota');return native(key,value);};assert.equal(r.history.saveSnapshot(),false);assert.ok(r.history.getSnapshot().loadIssue);assert.equal(r.history.getSnapshot().items.length,0);});
test('corrupt history is not repaired and foreign pending write blocks snapshot',async t=>{const r=await setup(t);r.rawStorage.setItem(r.runtime.history.key,'corrupt');assert.equal(r.history.saveSnapshot(),false);assert.equal(r.rawStorage.getItem(r.runtime.history.key),'corrupt');r.rawStorage.removeItem(r.runtime.history.key);r.runtime.storage.write('outbox',{id:'foreign'});assert.equal(r.history.saveSnapshot(),false);assert.equal(r.runtime.history.read().length,0);});
test('history uses existing twenty-item limit',async t=>{const r=await setup(t);for(let index=0;index<23;index++){r.runtime.store.command('rename',{name:`企画${index}`});assert.equal(r.history.saveSnapshot(),true);}assert.equal(r.history.getSnapshot().items.length,20);});
test('restore cancel unchecked and stale confirmation emit no intent',async t=>{const r=await setup(t);r.history.saveSnapshot();const item=r.runtime.history.read()[0];r.runtime.store.command('rename',{name:'変更'});let count=0;r.runtime.store.subscribeIntents(()=>count++);assert.equal(r.history.selectRestore(item),true);assert.equal((await r.history.confirmRestore({understood:false})).disposition,'unavailable');r.history.cancelConfirmation();assert.equal(count,0);r.history.selectRestore(item);r.runtime.store.command('rename',{name:'他者の変更'});const before=count;assert.equal((await r.history.confirmRestore({understood:true})).disposition,'conflict');assert.equal(count,before);assert.ok(r.history.getSnapshot().confirmation.stale);});
test('local restore and undo use one command and stop undo after any later business edit',async t=>{const r=await setup(t);r.history.saveSnapshot();const item=r.runtime.history.read()[0];r.runtime.store.command('rename',{name:'元に戻す対象'});const original=r.runtime.store.getSnapshot();r.history.selectRestore(item);assert.equal((await r.history.confirmRestore({understood:true})).disposition,'local');assert.equal(r.history.getSnapshot().canUndo,true);r.history.selectUndo();assert.equal((await r.history.confirmUndo({understood:true})).disposition,'local');assert.equal(r.runtime.store.getSnapshot().roomName,original.roomName);assert.equal(r.history.getSnapshot().canUndo,false);r.history.selectRestore(item);await r.history.confirmRestore({understood:true});r.runtime.store.command('rename',{name:'後続編集'});assert.equal(r.history.getSnapshot().canUndo,false);});
test('restore accepted after foreign participant addition does not enable undo',async t=>{const r=await setup(t,{shared:true});r.history.saveSnapshot();const item=r.runtime.history.read()[0];r.runtime.store.command('rename',{name:'変更'});await r.runtime.sync.flush();const original=r.transport.transaction;let release;const held=new Promise(resolve=>{release=resolve;});r.transport.transaction=async fn=>{await held;return original(fn);};r.history.selectRestore(item);const save=r.history.confirmRestore({understood:true});const remote=structuredClone(r.server.get());remote.participants.foreign={name:'他者追加',grade:1,updatedAt:200000};r.server.replace(remote);release();const result=await save;assert.ok(['saved','adjusted'].includes(result.disposition));assert.equal(r.history.getSnapshot().canUndo,false);assert.ok(r.runtime.store.getSnapshot().participants.foreign);});
test('restore retry never calls history restore twice and compact cache has no payload',async t=>{const r=await setup(t,{shared:true});r.history.saveSnapshot();const item=r.runtime.history.read()[0];r.runtime.store.command('rename',{name:'変更'});await r.runtime.sync.flush();r.transport.failOnce(Error('permission_denied'));let count=0;r.runtime.store.subscribeIntents(()=>count++);r.history.selectRestore(item);assert.equal((await r.history.confirmRestore({understood:true})).disposition,'failed');assert.equal(count,1);assert.equal((await r.operations.retry()).disposition,'saved');assert.equal(count,1);const record=r.cache.read().operation;assert.equal(record.receipt,undefined);assert.equal(record.patch,undefined);assert.equal(record.appliedRoom,undefined);});
test('history target mutation and new controller session invalidate restore and undo authority',async t=>{const r=await setup(t);r.history.saveSnapshot();const item=r.runtime.history.read()[0];r.history.selectRestore(item);r.rawStorage.setItem(r.runtime.history.key,JSON.stringify([{...item,data:{...item.data,roomName:'別のpayload'}}]));assert.equal((await r.history.confirmRestore({understood:true})).disposition,'conflict');r.history.cancelConfirmation();r.history.selectRestore(r.runtime.history.read()[0]);await r.history.confirmRestore({understood:true});const recovered=createProjectHistoryController({runtime:r.runtime,operations:r.operations,rawStorage:()=>r.rawStorage});t.after(recovered.dispose);assert.equal(recovered.getSnapshot().canUndo,false);});
test('failed undo consumes service backup and exact retry never executes undo again',async t=>{const r=await setup(t,{shared:true});r.history.saveSnapshot();const item=r.runtime.history.read()[0];r.runtime.store.command('rename',{name:'変更'});await r.runtime.sync.flush();r.history.selectRestore(item);assert.equal((await r.history.confirmRestore({understood:true})).disposition,'saved');assert.equal(r.history.getSnapshot().canUndo,true);r.history.selectUndo();r.transport.failOnce(Error('permission_denied'));let intents=0;r.runtime.store.subscribeIntents(()=>intents++);assert.equal((await r.history.confirmUndo({understood:true})).disposition,'failed');assert.equal(r.runtime.history.canUndo(),false);assert.equal(r.history.getSnapshot().canUndo,false);assert.equal((await r.operations.retry()).disposition,'saved');assert.equal(intents,1);});
test('restore leaves independent unshared drafts and an unchanged restore offers no undo',async t=>{const r=await setup(t);const record=r.cache.read();r.cache.write({...record,memoDraft:{raw:'未保存',openingMemo:'',resetGeneration:0},collectorDraft:{targetKey:'name:仮',context:'context',raw:'  控え '}},{expectedRevision:record.revision});r.history.saveSnapshot();const item=r.runtime.history.read()[0];r.history.selectRestore(item);assert.equal((await r.history.confirmRestore({understood:true})).disposition,'unchanged');assert.equal(r.history.getSnapshot().canUndo,false);assert.equal(r.cache.read().memoDraft.raw,'未保存');assert.equal(r.cache.read().collectorDraft.raw,'  控え ');});
