// Extract reviewed declarations, never execute the classic scripts in the app.
// Re-running with --check verifies source provenance and reproducibility.
import { parse } from 'acorn';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';

const root = new URL('../../../', import.meta.url);
const output = new URL('../src/domain/generated/', import.meta.url);
mkdirSync(output, { recursive: true });
const sources = {};
function source(path, wrapped = false) {
  const text = readFileSync(new URL(path, root), 'utf8');
  const ast = parse(text, { ecmaVersion: 'latest' });
  const body = wrapped ? ast.body[0].expression.callee.body.body : ast.body;
  sources[path] = { sha256: createHash('sha256').update(text).digest('hex'), declarations: [] };
  return { path, text, body };
}
function pick(src, predicate) {
  return src.body.filter(predicate).map(node => {
    sources[src.path].declarations.push(node.id?.name || node.declarations?.map(d => d.id.name).join(','));
    return src.text.slice(node.start, node.end);
  }).join('\n\n');
}
function declarations(node) { return node.type === 'FunctionDeclaration' || node.type === 'VariableDeclaration'; }
function named(names) { return node => names.includes(node.id?.name || node.declarations?.[0]?.id?.name); }
function exportAssignment(src, property) {
  const node = src.body.find(node => node.type === 'ExpressionStatement' && node.expression.type === 'AssignmentExpression' && node.expression.left.property?.name === property);
  if (!node) throw new Error(`Missing export ${property}`);
  return src.text.slice(node.expression.right.start, node.expression.right.end);
}
function emit(name, content) {
  const text = '// Generated by tools/extract-domain.mjs; edit the extraction boundary, not this file.\n' + content + '\n';
  // DOM access is forbidden even when the legacy declaration has a UI-oriented name.
  if (/document\.|querySelector|\.innerHTML|\.shadowRoot|\beval\(|new Function\(/.test(text)) throw new Error(`DOM or dynamic execution escaped into ${name}`);
  const path = new URL(name, output);
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== text) throw new Error(`Generated file drift: ${name}`);
  } else writeFileSync(path, text);
}

const canonical = source('assets/js/core/entity-state-v5.js');
emit('canonical.js', `export function createCanonicalEngine({ clock = { now: () => Date.now() } } = {}) {\nconst window = { SanpoClock: clock };\n${pick(canonical, declarations)}\nreturn ${exportAssignment(canonical, 'SanpoCanonicalState')};\n}`);

const roles = source('assets/js/core/allocation-role-state.js', true);
emit('roles.js', `export function withAllocationRoles(original) {\n${pick(roles, node => node.type === 'FunctionDeclaration' || named(['hasOwn', 'cloneWithoutGender', 'wrapped'])(node))}\nreturn wrapped;\n}`);

const parser = source('assets/js/features/google-form-import-parser.js', true);
emit('parser.js', `${pick(parser, declarations)}\nexport const formParser = ${exportAssignment(parser, 'SanpoFormImportParser')};`);

const state = source('assets/js/features/settlement/01-state.js');
const calculator = source('assets/js/features/settlement/02-calculator.js');
const excluded = ['readSettlementExtraTypeControlValue', 'ensureSettlementState', 'getRoomDataOnly', 'getSettlementCarRowsForDomSync', 'syncSettlementStateFromDOM', 'getSettlementSnapshot'];
const stateNodes = state.body.filter(node => declarations(node) && !excluded.includes(node.id?.name));
const stateNames = stateNodes.filter(node => node.id).map(node => node.id.name);
const calcNames = calculator.body.filter(node => node.id).map(node => node.id.name);
emit('settlement.js', `export function createSettlementDomain({ crypto = globalThis.crypto, random = Math.random, clientId = 'local' } = {}) {\nconst Math = Object.create(globalThis.Math); Math.random = random;\nconst window = { crypto };\nconst myClientId = clientId;\nconst getInt = value => parseInt(value) || 0;\nfunction ensureSettlementState() { throw new TypeError('Explicit settlement state is required'); }\nfunction getRoomDataOnly() { throw new TypeError('Explicit allocation data is required'); }\n${pick(state, node => stateNodes.includes(node))}\n${pick(calculator, declarations)}\nreturn { ${[...stateNames, ...calcNames].join(', ')} };\n}`);

const storage = source('assets/js/core/storage.js');
emit('migration.js', `export function createMigration(engine) {\nconst window = { SanpoCanonicalState: engine };\nconst APP_SCHEMA_VERSION = engine.SCHEMA_VERSION;\n${pick(storage, named(['migrateAppData']))}\nreturn migrateAppData;\n}`);

const sync = source('assets/js/core/sync-controller.js');
const syncExports = ['buildEntityPatch', 'buildSettlementIntentPatch', 'buildSettlementCarIntentPatch', 'buildSettlementSettingsIntentPatch', 'applyEntityPatchToObject', 'applyVersionedEntityPatch', 'compareSyncVersions', 'syncPathVersionKey', 'mergeConcurrentSettlementExtras', 'summarizeSyncOutcome', 'isUnsupportedRemoteSchema', 'isExpiredSyncOutbox', 'isPermanentSyncError', 'isTransactionRetryExhausted', 'patchHasDomainChanges', 'getSyncPathValue', 'buildConcurrentRoomMerge'];
// Dependency closure over top-level declarations. Transport / UI functions are not roots.
const byName = new Map(sync.body.filter(declarations).map(node => [node.id?.name || node.declarations[0].id.name, node]));
const selected = new Set();
function visit(name) {
  if (selected.has(name) || !byName.has(name)) return;
  selected.add(name);
  function walk(node) {
    if (!node || typeof node !== 'object') return;
    if (node.type === 'Identifier') visit(node.name);
    Object.values(node).forEach(value => { if (Array.isArray(value)) value.forEach(walk); else if (value && typeof value === 'object') walk(value); });
  }
  walk(byName.get(name));
}
syncExports.forEach(visit);
emit('sync.js', `export function createSyncDomain({ migrate, clock = { now: () => Date.now(), isServerAligned: () => false }, clientId }) {\nconst migrateAppData = migrate;\nconst window = { SanpoClock: clock };\nconst myClientId = clientId;\nconst APP_SCHEMA_VERSION = 6;\n${pick(sync, node => selected.has(node.id?.name || node.declarations?.[0]?.id?.name))}\nreturn { ${syncExports.join(', ')} };\n}`);

const random = source('assets/js/features/auto-assign.js');
emit('allocation.js', `export function createAssignmentDomain({ random = Math.random, clock = { now: () => Date.now() } } = {}) {\nconst Math = Object.create(globalThis.Math); Math.random = random;\n${pick(random, named(['shuffleArray', 'isRandomlyMovablePlacement', 'randomSlotsFromCanonical']))}\nfunction assign(room, type, engine) {\nconst allocation = room.allocations[type];\nengine.ensureAllParticipantsPlaced(allocation, room.participants || {});\nconst movableIds = Object.entries(allocation.placements || {}).filter(([id, placement]) => isRandomlyMovablePlacement(placement, room.participants?.[id])).map(([id]) => id);\nif (!movableIds.length) return false;\nconst now = clock.now();\nconst slots = shuffleArray(randomSlotsFromCanonical(allocation, room.participants || {}));\nconst shuffled = shuffleArray(movableIds);\nslots.forEach(slot => { const participantId = shuffled.shift(); if (participantId) allocation.placements[participantId] = { kind: 'member', driver: false, groupId: slot.groupId, order: slot.order, updatedAt: now }; });\nshuffled.forEach((participantId, order) => { allocation.placements[participantId] = { kind: 'waiting', driver: false, groupId: '', order, updatedAt: now }; });\nengine.ensureAllParticipantsPlaced(allocation, room.participants || {});\nreturn true;\n}\nreturn { assign, randomSlotsFromCanonical, isRandomlyMovablePlacement };\n}`);

const applicants = source('assets/js/features/form-applicant-sync-v2.js', true);
const applicantNames = ['validApplicationSync', 'applicantMeta', 'participantMeta', 'applicantEntries', 'participantIdForApplicant', 'makeDriverGroupId', 'ensureDriver', 'participantHasDependentData'];
emit('applicants.js', `export function createApplicantsDomain(canonical) {\nconst window = { SanpoCanonicalState: canonical };\nconst applicationSync = () => null;\n${pick(applicants, named(['APPLICATION_KIND', 'APPLICATION_VERSION', ...applicantNames]))}\nreturn { ${applicantNames.join(', ')} };\n}`);

const manifest = JSON.stringify(sources, null, 2) + '\n';
const manifestPath = new URL('../migration/domain-provenance.json', import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(manifestPath, 'utf8') !== manifest) throw new Error('Source provenance drift');
} else writeFileSync(manifestPath, manifest);
console.log(`Verified ${Object.keys(sources).length} legacy source boundaries.`);
